# Generated by Django 4.0.6 on 2022-07-27 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentry',
            old_name='Transaction',
            new_name='transaction',
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='Accounting.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('income', 'Income'), ('expense', 'Expense'), ('bill', 'Bill')], max_length=255),
        ),
    ]
