# Generated by Django 4.0.6 on 2022-07-28 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0002_rename_transaction_journalentry_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='Accounting.transaction'),
        ),
    ]
